# Generated by Django 4.2 on 2025-12-01 19:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='game_picture',
            field=models.ImageField(blank=True, default='profile_pics/no-image.jpg', null=True, upload_to='game_pics/'),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('10.00')), django.core.validators.MaxValueValidator(Decimal('999.99'))]),
        ),
    ]
