# Generated by Django 4.2 on 2025-11-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamemodel',
            name='image_url',
        ),
        migrations.AddField(
            model_name='gamemodel',
            name='game_picture',
            field=models.ImageField(blank=True, null=True, upload_to='game_pics/'),
        ),
    ]
