# Generated by Django 4.2 on 2025-12-11 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_gamemodel_game_picture_alter_gamemodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
